all:
	$(MAKE) -C bintree_v1
	$(MAKE) -C bintree_v2
	$(MAKE) -C bintree_v3
	$(MAKE) -C bintree_v4
	$(MAKE) -C bintree_v5
	$(MAKE) -C bintree_v6
	$(MAKE) -C bintree_v7
	$(MAKE) -C set_list_v1
	$(MAKE) -C set_tree_v1
	$(MAKE) -C set_tree_v2
	$(MAKE) -C set_tree_v3
