all:
	$(MAKE) -C 01_atributos_metodos
	$(MAKE) -C 02_constructores
	$(MAKE) -C 03_metodos_constantes
	$(MAKE) -C 04_stack_heap
	$(MAKE) -C 05_destructores
	$(MAKE) -C 06_constructor_copia
	$(MAKE) -C 07_sobrecarga_operadores
	$(MAKE) -C 08_operador_asignacion
	$(MAKE) -C 09_plantillas
	$(MAKE) -C 10_stl_lineales
	$(MAKE) -C 11_smart_pointers
	$(MAKE) -C 12_pair_y_tuple
	$(MAKE) -C 13_objetos_funcion
