all: juego1 juego2 juego3 juego

juego1: juego1.cpp
	g++ -o juego1 juego1.cpp

juego2: juego2.cpp
	g++ -o juego2 juego2.cpp

juego3: juego3.cpp ConjuntoChar.cpp
	g++ -o juego3 juego3.cpp ConjuntoChar.cpp

juego: juego.cpp ConjuntoChar.cpp
	g++ -o juego juego.cpp ConjuntoChar.cpp
